version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:latest
jobs:
  build:
    executor: node
    steps:
      - checkout
      - run:
          name: install packages
          command: npm i
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm run test-ci
  publish:
    executor: node
    steps:
      - checkout
      - run:
          name: install packages
          command: npm i
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm run test-ci
      - run:
          name: publish
          command: npx firebase deploy --only hosting --project ${FIREBASE_PROJECT_ID} --token ${FIREBASE_TOKEN}
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - publish:
          context: account-book-firebase-publish
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
