version: 2
jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run:
          name: install packages
          command: npm i
      - run:
          name: post install
          command: npm run postinstall
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm run test
